<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="/vendor/fontawesome/css/solid.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>




    <title>Inserir</title>
</head>

<body>
    
    <form action="/inserir/" method="post">
        <div class="container">
            <div class="col-md-6">
                <div class="configdiv">
                    <h1>Inserir Carro</h1>
                    <h2>Modelo:</h2>
                    <input type="text" name="modelo" require>
                    <h2>Marca:</h2>
                    <input type="text" name="marca" require><br>
                    <h2>Ano:</h2>
                    <input type="text" name="ano" require><br>


                    <div>
                    <button type="submit" value="Enviar" >Inserir</button>
                    </div>


                </div>
            </div>
</form>

</body>

<script src="vendor/jquery/jquery-3.4.1.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


</html>